### ISSUE TITLE
How do I handle deleted items from the source system that are orphaned in Fusion?

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#38] opened 2019-07-01 20:38 UTC
First time, you execute a fetch and your source system gives you 20 items.  You emit 20 documents.  Next index, 2 items were deleted from the source.  How do you handle the deletion of the orphans?  In the source system, the items are just gone - no record of the deletion (think table in database).  In the connector SDK, I cannot find any method to access the current collection (in order to delete it, read items from it, etc.)  How can you read through the items from the collection so that you can remove orphans?

**Comment by mwmitchell** [comment] 2019-07-01 20:48
Hi @eborisowIQVIA,

During a re-crawl, those items come back to the fetcher's fetch method. The source system would then be queried as before, but empty results (or maybe an error or 404 etc.) would indicate deletion. At that point, your fetcher would emit delete messages, which tells Fusion to remove the items from the crawl-db and content collections.

If this does not work for you, can you provide details on how your connector is implemented?

- Matt

**Comment by eborisowIQVIA** [comment] 2019-07-01 21:28
In the fetch method, I'm retrieving the current items from the target system.  For example, if I have a REST API that has an endpoint GET /items.  It will return only active items in the system.  During indexing, I emit a Document for each item.  During the next fetch, there is no fetchInput (other than a CheckPoint that I emit containing the last time when the job ran).  Other than that, there is no default item that is given to the fetch method.  What type of behavior is supposed to happen (re: _those items come back to the fetcher's fetch method_)?  I don't get any objects in 4.2.2.

**Comment by blorincz1** [comment] 2019-07-03 11:53
Hi @eborisowIQVIA, Matt is off today, but we looked into your use case and wanted to make sure we provided a response before the holiday. We've researched a few potential workarounds, but have confirmed the framework does not currently support using checkpoints _and_ sending previously crawled items to the fetch method on re-crawls. However, we do have a solution in mind and are actively discussing next steps to help get you moving forward. We'll be back in touch in a few days with details. Thanks for your patience!

- Bob

**Comment by mwmitchell** [comment] 2019-07-11 14:11
Hi @eborisowIQVIA - We've talked through the details of your requirements and are now working on a solution. Will keep you posted on any updates.

**Comment by mwmitchell** [comment] 2019-07-15 21:43
@eborisowIQVIA We're reviewing a proposal to address your needs now. There was a question about the input source your connector is crawling, which was essentially this:

Does the source data contain everything except removed items, including items that have not been modified since the last crawl? I think you answered that question here:

> [It will return only active items in the system.](https://github.com/lucidworks/connectors-sdk-resources/issues/38#issuecomment-507432578)

I wanted to confirm with you before moving forward.

- Matt

**Comment by eborisowIQVIA** [comment] 2019-07-15 22:32
@mwmitchell-There are usually two possible choices.  1) the source returns all current items or 2) the source accepts a parameter to allow you to filter the results using last modified or created date.  Option 2 is more difficult to handle for orphans and would probably need a ‘true-up’ query to handle all purging on a regular basis that is not incremental, but I’ll skip incremental crawl for now, if I can somehow delete the orphans.

**Comment by mwmitchell** [comment] 2019-07-16 14:42
Thanks @eborisowIQVIA, all making sense. Question on this:

> Option 2 is more difficult to handle for orphans and would probably need a ‘true-up’ query to handle all purging on a regular basis that is not incremental

Right, that sounds tricky, because if you are treating items that are missing as removals, then filtered items would also be deleted. And by 'true-up', you mean essentially a full content re-sync between Fusion and the source?

**Comment by eborisowIQVIA** [comment] 2019-07-16 20:45
@mwmitchell - Yep, so let's just focus on Option 1 for now.  Assume that we are just getting all of the 'active' items during each crawl.  My own personal preference - Give me an API that can provide a collection of the existing items in the data source during prefetch.  I can compare that collection to the results of the query from the primary data source.  With those two pieces of information, I can check which items are no longer there in the data source.  As a bonus, make the same collection available to the fetch method.

For Option 2 to work, I can see combining the process above with a separate incremental crawl where nothing is deleted, we only get new items.  In a perfect world, we would have two separately scheduled jobs - 1 that performs the incremental crawl and deletes nothing.  That job runs more frequently (few times an hour or so).  Then, a separate job that performs the true-up to purge items that no longer exist (runs less frequently).  It would be friendlier to the data source APIs by making less calls to those endpoints.

**Comment by mwmitchell** [comment] 2019-10-23 19:52
Based on the new "stray content deletion" feature we added to deal with this particular issue, I'm closing this one for now. Feel free to re-open or file a new issue if needed @eborisowIQVIA

**Closed by mwmitchell** 2019-10-23 19:52 UTC
Labels: help wanted, question
